name: GDesignz
favicon: null
layout_spectrum: 0.7654776084236801
typography_spectrum: 0.99413
title: Gfx Attax
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9992510243318975
  lightness: 0.25926080089993775
  saturation: 0.49587238673120737
  rhythmicContrast: 0.011024536099284887
purpose: []
